services:
  web:
    container_name: web_django_referral_system
    build:
      context: .
      dockerfile: ./compose/python/Dockerfile
    working_dir: /usr/src/app
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -b 0.0.0.0:8000 --reload --workers 1 --timeout 90 config.wsgi:application"
    volumes:
      - ./app/:/usr/src/app/:delegated
      - static_volume:/usr/src/app/static
    env_file:
      - ./app/.env
    depends_on:
      - postgres-db
    expose:
      - 8000
    networks:
      - django_network

  postgres-db:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    container_name: postgres-db_django_referral_system
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  redis:
    image: redis:7.2-alpine
    container_name: redis_django_referral_system
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - django_network

  nginx:
    container_name: nginx_django_referral_system
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/src/app/static:ro
    depends_on:
      - web
    networks:
      - django_network

volumes:
  postgres_data:
  static_volume:

networks:
  django_network:
    driver: bridge
